### PR TITLE
Update copyright footer text

### PR DESCRIPTION
**Pull request by EvanHerman**
- Introduce `Go\get_copyright_kses_html()` to retreive HTML markup allowed in the copyright section of the footer.
- Introduce `go_copyright_kses_html` filter to allow for the allowed HTML passed into `wp_kses` to be filtered.
- Updated `copyright` theme mod `sanitize_callback` to return `return wp_kses( $input, \Go\get_copyright_kses_html() );` instead of passing the value through `sanitize_text_field` (which strips out HTML markup).
- Introduce `go_footer_copyrght_year_text` filter and pass the copyright year footer text through that, to allow it to be customized or removed altogether. To hide the copyright year text, simply return an empty string.

#### Example Usage
```php
/**
 * Custom footer copyright text
 *
 * @param string $copyright_text Original theme mod copyright text from the customizer.
 *
 * @return string Filtered footer copyright text to display on front of site.
 */
function custom_copyright_text( $copyright_text ) {

	if ( is_admin() ) {

		return $copyright_text;

	}

	return $copyright_text . ' This is a <a href="#">test</a>.';

}
add_filter( 'theme_mod_copyright', 'custom_copyright_text', PHP_INT_MAX );

/**
 * Append a link after the copyright year.
 *
 * @param string $year_text Original copyright footer year text
 *
 * @return string Filtered copyright footer text.
 */
function custom_go_footer_copyrght_year_text( $footer_year_text ) {

	return $footer_year_text . '<a href="https://www.example.org">Testing</a>';

}
add_filter( 'go_footer_copyrght_year_text', 'custom_go_footer_copyrght_year_text' );

// Remove the copyright year
add_filter( 'go_footer_copyrght_year_text', '__return_empty_string' );
```

### CODE REVIEW

**Comment by EvanHerman** [comment]
@AnthonyLedesma 

The 'year text' filter (`go_footer_copyrght_year_text`) actually just removes the year, 2020. So if you just drop in what you have

```php
// Remove the copyright year
add_filter( 'go_footer_copyrght_year_text', '__return_empty_string' );
```

It will remove the year.

Similarly with:

```php
/**
 * Append a link after the copyright year.
 *
 * @param string $year_text Original copyright footer year text
 *
 * @return string Filtered copyright footer text.
 */
function custom_go_footer_copyrght_year_text( $footer_year_text ) {

	return $footer_year_text . '<a href="https://www.example.org">Testing</a>';

}
add_filter( 'go_footer_copyrght_year_text', 'custom_go_footer_copyrght_year_text' );
```

You'll just see a link 'Testing' next to the year.

**Comment by AnthonyLedesma** [comment]
@EvanHerman Using this filter as shown in the example I was not able to remove the year from the footer of the theme. The year persists when using this custom code.

**Comment by EvanHerman** [comment]
Interesting....when I add that filter to an MU it just drops the year.

image


Are you sure your URL doesn't include some customize-changeset UUID, or something is cached? 🤔

**Comment by EvanHerman** [comment]
I've tested this a few times yesterday and today. It looks like things are working as intended. If for some reason they are not after our release, we can revisit.

**Pull request merged**
