### PR TITLE
Re-enable checkbox images

### PR DESCRIPTION
**Pull request by EvanHerman**

### CODE REVIEW

**Comment by EvanHerman** [comment]
**Note:** The phpcs job failure will be fixed when #630 is merged.

**Review by AnthonyLedesma — DISMISSED** [review]
Found some strange behavior on the Form block when the page is also specified as the WooCommerce product page. 

**Regular post/page with Form block**
image

**Unable to check radio or checkbox when is product page also**
goCheckboxProductPage


To replicate this you can first test out a new post/page with the Form block. It should work as expected. Next, we can go into the WooCommerce settings and set the product page as the page with the Form on it. View store to see the issue.

**Review by AnthonyLedesma — CHANGES_REQUESTED** [review]
Looks like the Checkbox is working as expected but the Radio block is not yet working properly. 
Also, I see this alignment is a bit off. Perhaps it's a quick fix?
goProductPageCheckbox

**Review by AnthonyLedesma — APPROVED** [review]
Changes look good!

**Pull request merged**
