### PR TITLE
Add Hacktoberfest label

### PR DESCRIPTION
**Pull request by richtabor**
name: "Hacktoberfest"
color: "ff8ae2"
description: "Issues/PRs related to Hacktoberfest: https://hacktoberfest.digitalocean.com"

### CODE REVIEW

**Review by EvanHerman — APPROVED** [review]
Easy enough 👍

**Comment by EvanHerman** [comment]
I'm not sure why the unit tests are failing on this PR 🤔

**Comment by rungta08** [comment]
Is this still open??

**Comment by EvanHerman** [comment]
@rungta08 Yes, we are accepting PRs for Hacktoberfest. I've added the topic to the repo, so each individual PR doesn't need to be labeled.

**Pull request merged**
