### PR TITLE
Update content.php

### PR DESCRIPTION
**Pull request by andersbea**
Added a check to see whether the user is in the Blog page or a single post page. This ensures that the excerpt only displays on the Blog page instead of on both the Blog and Single post page.

### CODE REVIEW

**Comment by sarahjunefox** [comment]
Hi, any update on when this will happen?

**Comment by andersbea** [comment]
It will be up to the repository owners whether they accept the pull request and merge the change.

**Review by EvanHerman — APPROVED** [review]
Looks good, and working well on my end.

Thanks so much for your contribution @andersbea! 👍

**Comment by andersbea** [comment]
No problem, thank you for checking and approving

**Comment by sarahjunefox** [comment]
This is still not working on my site.

**Comment by andersbea** [comment]
@EvanHerman : Has this change been pushed to production?

**Pull request merged**
