### PR TITLE
Menu hover/click settings toggle

### LINKED ISSUE #529: menu-item isn’t working if submenu exist
**Describe the bug:**
If a menu-item (primary menu) has a submenu, the opening of the submenu works, but the link of the parent-menu-item cannot be executed. 

**Expected behavior:**
Maybe it would be better to open the submenu on the desktop directly after mouseover. So that the parent-menu-item is choosable.

**Priority** (select one):
- [X] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

### PR DESCRIPTION
**Pull request by EvanHerman**
Resolves #529

This PR introduces a new customizer setting `Menus > Menu Behavior > Show sub menus on hover.`. This is `false` (unchecked) by default, so sites that are currently using the theme will see no changes. New users, or those who want to show submenus on hover can enable this setting.

- [x] Unit tests have been added to maintain %100 coverage.
https://8245-196281488-gh.circle-artifacts.com/0/phpunit-coverage/phpunit/html/index.html

### Demo
menu-hover

### CODE REVIEW

**Comment by sirjonathan** [comment]
Just to confirm, will this allow the parent menu item to be clicked?

**Comment by richtabor** [comment]
Also, we should make this setting the default behavior (which will resolve the top-level menu item issue).

**Comment by EvanHerman** [comment]
@sirjonathan Correct. When the option is checked in the customizer, as outlined in the gif above, you'll be able to click the top level menu item.

**Comment by EvanHerman** [comment]
There still seems to be some weird behavior on mobile, and the 'hover to show sub menu items' doesn't currently work when using header 4. I'm also not sure how hover it should behave on mobile. There isn't technically a hover state on mobile like there is when using a mouse.

**Comment by sirjonathan** [comment]
I'm happy to test this before you push it out, if it's helpful! Just point me in the right direction?

**Review by richtabor — APPROVED** [review]

**Comment by richtabor** [comment]
I think we'll follow up with a few more tweaks for mobile, but its fine in its current form.

**Pull request merged**
