### PR TITLE
Add layouts for use with CoBlocks layout selector

### PR DESCRIPTION
**Pull request by AnthonyLedesma**
Added in https://github.com/godaddy-wordpress/coblocks/pull/1473 the Layout selector controls allow for extending using custom templates.

This PR adds templates to the theme root (`coblocks/layouts/*.php`).

### CODE REVIEW

**Comment by richtabor** [comment]
@AnthonyLedesma What kind of changes are we needing?

**Comment by AnthonyLedesma** [comment]
At the time of working this PR the https://github.com/godaddy-wordpress/coblocks/pull/1473 is not properly importing the templates from Go. 

https://github.com/godaddy-wordpress/coblocks/blob/91b8c93d1f925779c1a017f213b5790bb448e19b/src/layout-selector/index.php#L8-L30

The existing logic is looking for templates in a `.php` format as opposed to `.js`. Need to convert logic to import templates in a JavaScript format.

**Comment by jrtashjian** [comment]
@AnthonyLedesma Looks like the layouts aren't in the correct format which is probably why it wasn't loading into the layout selector. Here is an example:

```php
<?php

return array(
	'category' => array( 'Meet the team' ),
	'label'    => __( 'Meet the team', 'go' ),
	'blocks'   => array(
		array(
			'core/spacer',
			array(
				'height' => '60',
			),
			array(),
		),
		array(
			'core/heading',
			array(
				'align'           => 'center',
				'content'         => 'This is some custom text for the custom layout.',
				'level'           => 2,
				'fontWeight'      => '',
				'textTransform'   => '',
				'noBottomSpacing' => false,
				'noTopSpacing'    => false,
			),
			array(),
		),
		array(
			'core/spacer',
			array(
				'height' => 20,
			),
			array(),
		),
		array(
			'core/image',
			array(
				'align'           => 'wide',
				'url'             => 'https://images.unsplash.com/photo-1585188968708-540006b4cd51?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80',
				'alt'             => 'Image description',
				'caption'         => '',
				'id'              => 1,
				'sizeSlug'        => 'full',
				'linkDestination' => 'none',
				'className'       => 'is-style-default',
				'noBottomMargin'  => false,
				'noTopMargin'     => false,
				'cropX'           => 0,
				'cropY'           => 0,
				'cropWidth'       => 100,
				'cropHeight'      => 100,
				'cropRotation'    => 0,
			),
			array(),
		),
		array(
			'core/image',
			array(
				'align'           => 'wide',
				'url'             => 'https://images.unsplash.com/photo-1585216658790-094546fa88e1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1955&q=80',
				'alt'             => 'Image description',
				'caption'         => '',
				'id'              => 1,
				'sizeSlug'        => 'full',
				'linkDestination' => 'none',
				'className'       => 'is-style-default',
				'noBottomMargin'  => false,
				'noTopMargin'     => false,
				'cropX'           => 0,
				'cropY'           => 0,
				'cropWidth'       => 100,
				'cropHeight'      => 100,
				'cropRotation'    => 0,
			),
			array(),
		),
		array(
			'core/columns',
			array(
				'align' => 'wide',
			),
			array(
				array(
					'core/column',
					array(
						'width' => 20,
					),
					array(),
				),
				array(
					'core/column',
					array(
						'width' => 60,
					),
					array(
						array(
							'core/heading',
							array(
								'align'           => 'center',
								'content'         => 'Reimagine home. We’ll help you find a place you’ll love.',
								'level'           => 3,
								'fontWeight'      => '',
								'textTransform'   => '',
								'noBottomSpacing' => false,
								'noTopSpacing'    => false,
							),
							array(),
						),
						array(
							'core/paragraph',
							array(
								'align'           => 'center',
								'content'         => 'Connecting audience + artist in our lush, speakeasy-style listening room. Only 50 seats available for this sought-after scene.',
								'dropCap'         => false,
								'fontWeight'      => '',
								'textTransform'   => '',
								'noBottomSpacing' => false,
								'noTopSpacing'    => false,
							),
							array(),
						),
					),
				),
				array(
					'core/column',
					array(
						'width' => 20,
					),
					array(),
				),
			),
		),
		array(
			'coblocks/services',
			array(
				'columns'      => 2,
				'gutter'       => 'huge',
				'align'        => 'wide',
				'headingLevel' => 5,
				'buttons'      => false,
				'className'    => 'alignwide is-style-threebyfour',
			),
			array(
				array(
					'coblocks/service',
					array(
						'headingLevel' => 5,
						'showCta'      => false,
						'imageUrl'     => 'https://user-images.githubusercontent.com/1813435/76585533-fffec900-64b4-11ea-9ba4-fb771f6d7622.jpg',
						'imageAlt'     => 'Image description',
						'alignment'    => 'none',
					),
					array(
						array(
							'core/heading',
							array(
								'content'         => 'A social house',
								'level'           => 4,
								'fontWeight'      => '',
								'textTransform'   => '',
								'noBottomSpacing' => false,
								'noTopSpacing'    => false,
							),
							array(),
						),
						array(
							'core/paragraph',
							array(
								'content'         => "With our guides' experience, we will not only get you to where the fish are - but we'll get you hooked on them too. Our crew is knowledgeable and friendly - ready to take you on the trip of your dreams.",
								'dropCap'         => false,
								'fontWeight'      => '',
								'textTransform'   => '',
								'noBottomSpacing' => false,
								'noTopSpacing'    => false,
							),
							array(),
						),
					),
				),
				array(
					'coblocks/service',
					array(
						'headingLevel' => 5,
						'showCta'      => false,
						'imageUrl'     => 'https://user-images.githubusercontent.com/1813435/76585544-04c37d00-64b5-11ea-93a2-e287301b67f0.jpg',
						'imageAlt'     => 'Image description',
						'alignment'    => 'none',
					),
					array(
						array(
							'core/heading',
							array(
								'content'         => 'A listening room',
								'level'           => 5,
								'fontWeight'      => '',
								'textTransform'   => '',
								'noBottomSpacing' => false,
								'noTopSpacing'    => false,
							),
							array(),
						),
						array(
							'core/paragraph',
							array(
								'content'         => 'Folks have fought some monster bluefin tuna on standup gear with our offshore fishing packager, which is an incredible challenge for sure! Stick to the shoreline and test your strength pulling in some biggies!',
								'dropCap'         => false,
								'fontWeight'      => '',
								'textTransform'   => '',
								'noBottomSpacing' => false,
								'noTopSpacing'    => false,
							),
							array(),
						),
					),
				),
			),
		),
	),
);
```

We also shouldn't have to put this in one format or another as CoBlocks will take the PHP array format and convert it to json for use in JS.

**Comment by richtabor** [comment]
@AnthonyLedesma Contact forms need their corresponding submit buttons. 
Screen Shot 2020-05-28 at 6 11 50 PM

**Comment by AnthonyLedesma** [comment]
Nice catch!

**Comment by AnthonyLedesma** [comment]
Updated submit buttons to contact layouts. The outstanding issues with images are related to network requests from the hosting server. Local placeholder images will solve that issue.

**Comment by AnthonyLedesma** [comment]
I was able to swap images for locally hosted placeholder images within the templates. It works as expected but there are a few outstanding issues that need to be resolved. 

Media Card block uses HTML markup to determine attribute values. Having issues setting custom values/ need advice.

Hero block crashing due to issue reported [here](https://github.com/godaddy-wordpress/coblocks/pull/1515)

**Comment by richtabor** [comment]
Removed the styles and added them to https://github.com/godaddy-wordpress/go/pull/533

**Pull request merged**
