### PR TITLE
Introduce WooCommerce cart menu icon

### PR DESCRIPTION
**Pull request by EvanHerman**
Introduce new filters to manage the WooCommerce cart menu icon/text.
- `go_wc_show_cart_menu` - Boolean - Default: `true` - False to disable the output of the cart menu item.
- `go_menu_cart_text` - String - Filter the text for the cart menu item.
- `go_menu_cart_url` - String - Filter the URL for the cart menu item.

```php
/**
 * Set a custom URL for the cart menu item.
 *
 * @param  string $url URL to send the customer to, when clicked.
 *
 * @return string Filtered URL.
 */
function go_custom_menu_cart_url( $url ) {

	return 'https://www.google.com';

}
add_filter( 'go_menu_cart_url', 'go_custom_menu_cart_url' );

/**
 * Set a custom text for the cart menu item.
 *
 * @param  string $text Cart menu item text.
 *
 * @return string Filtered cart menu item text.
 */
function go_custom_menu_cart_text( $text ) {

	return __( 'Cart', 'text-domain' );

}
add_filter( 'go_menu_cart_text', 'go_custom_menu_cart_text' );

/**
 * Disable the Go WooCommerce cart menu item
 *
 * @var bool
 */
add_filter( 'go_wc_show_cart_menu', '__return_false' );
```

___________ 

image

### CODE REVIEW

**Comment by richtabor** [comment]
This is so good, though I think we should split this out as a template tag - placing it outside the navigation - for a couple reasons. 

1. The SVG makes the list items not display properly (unless the icon is smaller than the text, which doesn't work). 
Screen Shot 2019-10-22 at 5 57 41 PM

2. The cart icon does not display on Header-4, when the menu is behind the "..." icon.

**Comment by EvanHerman** [comment]
@richtabor I think having it outside of the main navigation could work. I tried to append it onto the main nav so we wouldn't have to introduce too many new styles to make things work. I can tweak this and break it out into a template tag like we have the search icon being generated.

**Comment by EvanHerman** [comment]
@richtabor After working on this a bit and moving it out of the nav - it looks like placing this icon up in the header is a little trickier as each header style is different. I'll push up what I've got and you can take a look.

**Comment by EvanHerman** [comment]
I added the cart icon to Header variation 1 - no other headers show it at the moment.

**Comment by EvanHerman** [comment]
Ok - I'm back and forth with this one. I'm leaning towards appending it onto the navigation as the better solution. I think it fits in with the site flow better, without having to introduce too many new styles into the mix. 

As for your concerns above:
1. We can add a `top: 5px;` to the icon to align it properly with the rest of the navigation text.
2. The icon isn't showing up on any mobile menu or menus being the '...' because the fill color is set to `hsla(var(--theme-site-nav--color), 1);`. We'll need to just add the following to fix that issue:
```css
.has-offscreen-nav .menu-item-go-woo-cart svg {
	fill: hsl(var(--theme-offscreen-nav--color));
}
```

**Comment by EvanHerman** [comment]
:shipit:

**Pull request merged**
